set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_OSX_ARCHITECTURES arm64)

if(PORT STREQUAL "secp256k1")
  list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS
    -DSECP256K1_ENABLE_MODULE_ECDH=OFF
    -DSECP256K1_ENABLE_MODULE_ELLSWIFT=OFF
    -DSECP256K1_ENABLE_MODULE_EXTRAKEYS=ON
    -DSECP256K1_ENABLE_MODULE_MUSIG=OFF
    -DSECP256K1_ENABLE_MODULE_RECOVERY=OFF
    -DSECP256K1_ENABLE_MODULE_SCHNORRSIG=ON
  )
endif()
